#!/bin/bash

. ./config.sh
~/bin/bisq/bisq-desktop --baseCurrencyNetwork=RADC_REGTEST --useLocalhostForP2P=true --useDevPrivilegeKeys=true --nodePort=5555 --appName=bisq-RADC_REGTEST_Alice --daoActivated=$dao --genesisBlockHeight=$genesis_height --genesisTxId=$genesis_tx
