#!/bin/bash

. ./config.sh
~/bin/bisq/bisq-desktop --baseCurrencyNetwork=RADC_REGTEST --useLocalhostForP2P=true --useDevPrivilegeKeys=true --nodePort=6666 --appName=bisq-RADC_REGTEST_Bob --daoActivated=$dao --genesisBlockHeight=$genesis_height --genesisTxId=$genesis_tx
